<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="8" passed="7" failed="0" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-01-18T03:54:30Z" name="Default suite" finished-at="2021-01-18T03:54:38Z" duration-ms="7440">
    <groups>
    </groups>
    <test started-at="2021-01-18T03:54:30Z" name="Default test" finished-at="2021-01-18T03:54:38Z" duration-ms="7440">
      <class name="com.planit.qa.test.Test001">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.planit.qa.test.Test001@21282ed8]" started-at="2021-01-18T14:54:30Z" name="setUp" finished-at="2021-01-18T14:54:36Z" duration-ms="5835" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="clickonContact()[pri:1, instance:com.planit.qa.test.Test001@21282ed8]" started-at="2021-01-18T14:54:36Z" name="clickonContact" finished-at="2021-01-18T14:54:37Z" duration-ms="244" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickonContact -->
        <test-method signature="clickonSubmit()[pri:2, instance:com.planit.qa.test.Test001@21282ed8]" started-at="2021-01-18T14:54:37Z" name="clickonSubmit" finished-at="2021-01-18T14:54:37Z" duration-ms="256" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickonSubmit -->
        <test-method signature="verifyError1()[pri:3, instance:com.planit.qa.test.Test001@21282ed8]" started-at="2021-01-18T14:54:37Z" name="verifyError1" finished-at="2021-01-18T14:54:37Z" duration-ms="32" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyError1 -->
        <test-method signature="verifyError2()[pri:4, instance:com.planit.qa.test.Test001@21282ed8]" started-at="2021-01-18T14:54:37Z" name="verifyError2" finished-at="2021-01-18T14:54:37Z" duration-ms="15" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyError2 -->
        <test-method signature="verifyError3()[pri:5, instance:com.planit.qa.test.Test001@21282ed8]" started-at="2021-01-18T14:54:37Z" name="verifyError3" finished-at="2021-01-18T14:54:37Z" duration-ms="14" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyError3 -->
        <test-method signature="validateCreateNewContact(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:6, instance:com.planit.qa.test.Test001@21282ed8]" started-at="2021-01-18T14:54:37Z" name="validateCreateNewContact" data-provider="getTestData" finished-at="2021-01-18T14:54:37Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Row.getCell(int)" because the return value of "org.apache.poi.ss.usermodel.Sheet.getRow(int)" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Row.getCell(int)" because the return value of "org.apache.poi.ss.usermodel.Sheet.getRow(int)" is null
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:115)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:509)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1308)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1036)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1126)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Row.getCell(int)" because the return value of "org.apache.poi.ss.usermodel.Sheet.getRow(int)" is null
	at com.planit.qa.util.TestUtil.getTestData(TestUtil.java:55)
	at com.planit.qa.test.Test001.getTestData(Test001.java:80)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:55)
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
	... 22 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateNewContact -->
        <test-method signature="errormessageGone()[pri:7, instance:com.planit.qa.test.Test001@21282ed8]" started-at="2021-01-18T14:54:37Z" name="errormessageGone" finished-at="2021-01-18T14:54:37Z" duration-ms="34" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- errormessageGone -->
        <test-method signature="successmsgverification()[pri:8, instance:com.planit.qa.test.Test001@21282ed8]" started-at="2021-01-18T14:54:37Z" name="successmsgverification" finished-at="2021-01-18T14:54:37Z" duration-ms="11" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- successmsgverification -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.planit.qa.test.Test001@21282ed8]" started-at="2021-01-18T14:54:37Z" name="teardown" finished-at="2021-01-18T14:54:38Z" duration-ms="571" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.planit.qa.test.Test001 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
